### ISSUE TITLE
First letters do not load correctly

### ISSUE THREAD

**Issue by remimestdagh** [msabrowser/msabrowser#12]
Hi

When using the MSAbrowser we are facing an issue where the first few letters stay gray until we scroll to the right and back. Any idea how we can resolve this?

![image](https://github.com/thekaplanlab/msabrowser/assets/47556303/93fae688-44ce-4331-b33e-7f0ef6a619af)

Kind regards
Remi

**Comment by furkanmtorun** [comment]
Hi Remi,

The developers of this project voluntarily try to contribute to this project. We will have a look at the issue.

All the best,
Furkan

**Comment by halilbilgin** [comment]
Hi @remimestdagh which browser and operating system are you using? Thanks

**Comment by remimestdagh** [comment]
We are using windows 11 and Firefox. The same happens on Chrome and Edge too. We are using it in React 18.

Thank!
