### ISSUE TITLE
Phylogenetic tree

### ISSUE THREAD

**Issue by MrTomRod** [msabrowser/msabrowser#2]
Hello!

I am considering to integrate this library into [my software](https://opengenomebrowser.github.io/opengenomebrowser/).

Are you planning to add support for phylogenetic trees? (Maybe, you could use [phylotree.js](https://github.com/veg/phylotree.js/) as used by [alignment.js](https://github.com/veg/alignment.js) to do the heavy lifting.)

It would make your already fantastic software complete from my perspective.

Best, MrTomRod

**Comment by furkanmtorun** [comment]
Dear Thomas Roder (@MrTomRod ),

Firstly, thank you very much for your contribution and feedback.
Also, we are happy to hear that you like our tool!

As for your suggestion, we have added your request to our plan and try to consider it during updates. 

Yours sincerely,
Furkan
