### ISSUE TITLE
My sequence is not displayed successfully

### ISSUE THREAD

**Issue by Shen-Jing** [msabrowser/msabrowser#3]
Hello!

Thank you for developing this tool.

The following are the problems I encountered.

### My data

[My data](https://raw.githubusercontent.com/Shen-Jing/Shen-Jing.github.io/master/assets/winsize_500.txt)

### HTML

(This is modified with reference to [examples](https://github.com/thekaplanlab/msabrowser/tree/master/examples).)

```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>MSABrowser | Spike Proteins Example</title>
    <link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/gh/msabrowser/msabrowser@v1.0//css/style.css" media="screen" />
    <script src="https://html2canvas.hertzen.com/dist/html2canvas.min.js" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/msabrowser/msabrowser@v1.0//javascript/msabrowser.js"></script>
</head>

<body>
    <h1>MSABrowser for Spike Proteins Example</h1>
    <article>
        In this example, spike proteins are retrieved and aligned.
        <br> Additionaly, some genetic variations and modifications are also added.
        <br> For example, you can view a<a href="javascript:void(0)" onclick="viewer.scrollToPosition(2,474)"> particular modification or variation</a> in a protein.
    </article>

    <!-- MSABrowser Demo -->
    <section id="MSABrowserDemo"></section>
    <!-- end of MSABrowser Demo -->


    <script type="text/javascript" charset="utf-8">
        var viewer;

        $.get("https://raw.githubusercontent.com/Shen-Jing/Shen-Jing.github.io/master/assets/winsize_500.txt", (fasta) => {

            viewer = new MSABrowser({
                id: "MSABrowserDemo",
                msa: MSAProcessor({
                    fasta: fasta,
                    hasConsensus: true
                }),
                colorSchema: "hydrophobicity",
            });

            viewer.export("MSA_export.fasta");

        });
    </script>
</body>

</html>
```

### Output

![image](https://user-images.githubusercontent.com/9480153/117534073-77c97480-b022-11eb-912f-610a9ed4beb3.png)

Sequences are not displayed.

I don't know where I did wrong.

Thanks,
Jing

**Comment by furkanmtorun** [comment]
Dear Shen-Jing (@Shen-Jing ),

First of all, thank you very much for giving a try on MSABrowser and your feedback is well appreciated.
Also, we apologize for this issue.

We are currently investigating the issue underlying this problem.
Once we are done, we will perform the updates and let you know.

Thanks for your patient!

Best,
Furkan

**Comment by Shen-Jing** [comment]
Hi Furkan,

Understood. Thank you for your very prompt response!

**Comment by halilbilgin** [comment]
Hi @Shen-Jing , The problem now should be fixed. Just let us know if you think there is another problem.

Thanks
